#!/bin/bash
. 4Gbot-source

if [ $# -ne 5 ] ; then
    echo -e "${RED}Usage: 4Gbot-pre keyfile botip masterip masteruser mastersshport${SET}"
    exit
else
    FOURGBOTKEYFILE="${1}"
    FOURGBOTBOTIP="${2}"
    FOURGBOTMASTERIP="${3}"
    FOURGBOTMASTERUSER="${4}"
    FOURGBOTMASTERSSHPORT="${5}"
    echo -e "${FOURGBOTGREEN}ssh key file name          : $FOURGBOTKEYFILE${FOURGBOTSET}"
    echo -e "${FOURGBOTGREEN}bot ip                     : $FOURGBOTBOTIP${FOURGBOTSET}"
    echo -e "${FOURGBOTGREEN}master ip                  : $FOURGBOTMASTERIP${FOURGBOTSET}"
    echo -e "${FOURGBOTGREEN}master ssh user            : $FOURGBOTMASTERUSER${FOURGBOTSET}"
    echo -e "${FOURGBOTGREEN}master ssh port            : $FOURGBOTMASTERSSHPORT${FOURGBOTSET}"
fi

ssh-keygen -b 4096 -f $FOURGBOTDIR/backup/$FOURGBOTKEYFILE -C $FOURGBOTKEYFILE
ssh-add -K $FOURGBOTDIR/backup/$FOURGBOTKEYFILE
ssh-copy-id -i $FOURGBOTDIR/backup/$FOURGBOTKEYFILE root@$FOURGBOTBOTIP
ssh-copy-id -i $FOURGBOTDIR/backup/$FOURGBOTKEYFILE $FOURGBOTMASTERUSER@$FOURGBOTMASTERIP
scp $FOURGBOTDIR/backup/$FOURGBOTKEYFILE* root@$FOURGBOTBOTIP:/root/.ssh
scp $FOURGBOTDIR/backup/$FOURGBOTKEYFILE* $FOURGBOTMASTERUSER@$FOURGBOTMASTERIP:./.ssh
