#!/bin/bash
. 4Gbot-source

if [ $# -eq 0 ] ; then
    if [ "$FOURGBOTINTERACTIVE" == "NONINTERACTIVE" ] ; then
        :
    elif [ "$FOURGBOTINTERACTIVE" != "INTERACTIVE" ] ; then
        echo -e "${RED}Usage: ./4Gbot-init botname operator apn usbdevice keyfile masterip masteruser mastersshport mastersshtunnelport mastervnctunnelport${SET}"
        exit
    fi
elif [ $# -ne 10 ] ; then
    echo -e "${RED}Usage: ./4Gbot-init botname \"operator\" \"apn\" usbdevice keyfile masterip masteruser mastersshport mastersshtunnelport mastervnctunnelport${SET}"
    exit
else
    FOURGBOTINTERACTIVE='NONINTERACTIVE'
    FOURGBOTBOTNAME="${1}"
    FOURGBOTOPERATOR="${2}"
    FOURGBOTAPN="${3}"
    FOURGBOTDEVICE="${4}"
    FOURGBOTKEYFILE="${5}"
    FOURGBOTMASTERIP="${6}"
    FOURGBOTMASTERUSER="${7}"
    FOURGBOTMASTERSSHPORT="${8}"
    FOURGBOTMASTERSSHTUNNELPORT="${9}"
    FOURGBOTMASTERVNCTUNNELPORT="${10}"
fi
echo -e "${FOURGBOTGREEN}interactive                : $FOURGBOTINTERACTIVE${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}bot name                   : $FOURGBOTBOTNAME${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}operator                   : $FOURGBOTOPERATOR${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}apn                        : $FOURGBOTAPN${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}device                     : $FOURGBOTDEVICE${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}ssh key file name          : $FOURGBOTKEYFILE${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}master ip                  : $FOURGBOTMASTERIP${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}master ssh user            : $FOURGBOTMASTERUSER${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}master ssh port            : $FOURGBOTMASTERSSHPORT${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}ssh tunnel port on master  : $FOURGBOTMASTERSSHTUNNELPORT${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}vnc tunnel port on master  : $FOURGBOTMASTERVNCTUNNELPORT${FOURGBOTSET}"
echo -e "${FOURGBOTGREEN}timestamp                  : $FOURGBOTRUNTIME${FOURGBOTSET}"


initSwap
initSsh
initTimezone
initInstall
initServices
initFtp
initDhclient
initHost
addBin
addScreenrc
initVnc
initPpp
initAutossh
